### ISSUE TITLE
JavaRuntimeEnvironment - JdkDefaultValueService.compute() has failed

### ISSUE THREAD

**Issue by normanm-algonquin** [payara/ecosystem-eclipse-plugin#10]
In am using '2019-03' with 'jee.product' running under Amazon's latest-&-greatest
JDK 8 'Corretto' OpenJDK package:

`
java.runtime.name=OpenJDK Runtime Environment
java.runtime.version=1.8.0_212-b04
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=1.8
java.vendor=Amazon.com Inc.
java.vendor.url=https://aws.amazon.com/corretto/
java.vendor.url.bug=https://github.com/corretto/corretto-8/issues/
java.version=1.8.0_212
java.vm.info=mixed mode
java.vm.name=OpenJDK 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.8
java.vm.vendor=Amazon.com Inc.
java.vm.version=25.212-b04
`

Is this related to the 'grizzly-npn-bootstrap' stuff?

Stacktrace from Error log
`java.lang.RuntimeException: IPayaraRuntimeModel.JavaRuntimeEnvironment: JdkDefaultValueService.compute() has failed
	at org.eclipse.sapphire.services.DataService.refresh(DataService.java:130)
	at org.eclipse.payara.tools.sapphire.PayaraServerConfigServices$JdkDefaultValueService.access$0(PayaraServerConfigServices.java:1)
	at org.eclipse.payara.tools.sapphire.PayaraServerConfigServices$JdkDefaultValueService$1.handleTypedEvent(PayaraServerConfigServices.java:145)
	at org.eclipse.payara.tools.sapphire.PayaraServerConfigServices$JdkDefaultValueService$1.handleTypedEvent(PayaraServerConfigServices.java:1)
	at org.eclipse.sapphire.FilteredListener.handle(FilteredListener.java:35)
	at org.eclipse.sapphire.EventDeliveryJob.run(EventDeliveryJob.java:52)
	at org.eclipse.sapphire.JobQueue.process(JobQueue.java:94)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:126)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:132)
	at org.eclipse.sapphire.Property.broadcast(Property.java:780)
	at org.eclipse.sapphire.Property.refreshValidation(Property.java:282)
	at org.eclipse.sapphire.Property$5.handle(Property.java:242)
	at org.eclipse.sapphire.EventDeliveryJob.run(EventDeliveryJob.java:52)
	at org.eclipse.sapphire.JobQueue.process(JobQueue.java:94)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:126)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:132)
	at org.eclipse.sapphire.services.Service.broadcast(Service.java:126)
	at org.eclipse.sapphire.services.Service.broadcast(Service.java:131)
	at org.eclipse.sapphire.services.DataService.refresh(DataService.java:152)
	at org.eclipse.sapphire.services.ValidationService$1.handleTypedEvent(ValidationService.java:35)
	at org.eclipse.sapphire.services.ValidationService$1.handleTypedEvent(ValidationService.java:1)
	at org.eclipse.sapphire.FilteredListener.handle(FilteredListener.java:35)
	at org.eclipse.sapphire.EventDeliveryJob.run(EventDeliveryJob.java:52)
	at org.eclipse.sapphire.JobQueue.process(JobQueue.java:94)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:126)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:132)
	at org.eclipse.sapphire.services.Service.broadcast(Service.java:126)
	at org.eclipse.sapphire.services.Service.broadcast(Service.java:131)
	at org.eclipse.sapphire.services.DataService.refresh(DataService.java:152)
	at org.eclipse.sapphire.services.ValidationService$1.handleTypedEvent(ValidationService.java:35)
	at org.eclipse.sapphire.services.ValidationService$1.handleTypedEvent(ValidationService.java:1)
	at org.eclipse.sapphire.FilteredListener.handle(FilteredListener.java:35)
	at org.eclipse.sapphire.EventDeliveryJob.run(EventDeliveryJob.java:52)
	at org.eclipse.sapphire.JobQueue.process(JobQueue.java:94)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:126)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:132)
	at org.eclipse.sapphire.Property.broadcast(Property.java:780)
	at org.eclipse.sapphire.Value.refreshContent(Value.java:159)
	at org.eclipse.sapphire.Value.refresh(Value.java:73)
	at org.eclipse.sapphire.Value.write(Value.java:475)
	at org.eclipse.sapphire.Value.write(Value.java:429)
	at org.eclipse.payara.tools.sapphire.IPayaraRuntimeModel$Impl.setName(Unknown Source)
	at org.eclipse.payara.tools.sapphire.PayaraServerConfigServices$ServerLocationListener.handle(PayaraServerConfigServices.java:238)
	at org.eclipse.sapphire.EventDeliveryJob.run(EventDeliveryJob.java:52)
	at org.eclipse.sapphire.JobQueue.process(JobQueue.java:94)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:126)
	at org.eclipse.sapphire.ListenerContext.broadcast(ListenerContext.java:132)
	at org.eclipse.sapphire.Property.broadcast(Property.java:780)
	at org.eclipse.sapphire.Value.refreshContent(Value.java:159)
	at org.eclipse.sapphire.Value.refresh(Value.java:73)
	at org.eclipse.sapphire.Value.write(Value.java:475)
	at org.eclipse.sapphire.ui.forms.BrowseActionHandler.run(BrowseActionHandler.java:51)
	at org.eclipse.sapphire.ui.SapphireActionHandler.execute(SapphireActionHandler.java:95)
	at org.eclipse.sapphire.ui.forms.swt.SapphireToolBarActionPresentation$1.widgetSelected(SapphireToolBarActionPresentation.java:113)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4363)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4150)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3767)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.wst.server.ui.internal.cnf.ServersView2$1.widgetSelected(ServersView2.java:118)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4363)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Widget.java:1585)
	at org.eclipse.swt.widgets.Link.textView_clickOnLink_atIndex(Link.java:798)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6584)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:235)
	at org.eclipse.swt.widgets.Widget.mouseDownSuper(Widget.java:1146)
	at org.eclipse.swt.widgets.Widget.mouseDown(Widget.java:1138)
	at org.eclipse.swt.widgets.Control.mouseDown(Control.java:2621)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6038)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:235)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2158)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2413)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6162)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5396)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5553)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:131)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3764)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)
Caused by: java.lang.IllegalArgumentException: Exception in thread "main" java.lang
	at org.eclipse.sapphire.Version.<init>(Version.java:77)
	at org.eclipse.sapphire.VersionConstraint.check(VersionConstraint.java:373)
	at org.eclipse.payara.tools.utils.JdtUtil$JvmValidator.version(JdtUtil.java:143)
`

**Comment by zakki** [comment]
This is because `org.eclipse.payara.tools.jver` is compiled targeting Java 1.8.
If JDK 1.7 or older exists in "Installed JREs", PayaraTools tries to parse error message (for example  "java.lang.UnsupportedClassVersionError: org/eclipse/payara/tools/jver/JavaVersionDetector ...") as version number, and it dies.

**Comment by fturizo** [comment]
Older issue that seems abandoned, closing. If issues are still present, raise the request on the [Ecosystem Support repository](https://github.com/payara/ecosystem-support)
