### ISSUE TITLE
Unable to start server due NumberFormatException

### ISSUE THREAD

**Issue by hjoeren** [payara/ecosystem-eclipse-plugin#17]
### Description

While trying to start a payara server 5.193.1 in the eclipse servers view an error occurs and it's said:

> Unable to start server due following issues:
For input string: "232-ea"

### Log

Here's the snipped of the eclipse log:

```
!ENTRY org.eclipse.payara.tools 4 150 2019-10-21 19:10:51.078
!MESSAGE Unable to start server due following issues:
!STACK 0
java.lang.NumberFormatException: For input string: "232-ea"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at org.eclipse.payara.tools.sdk.server.JDK.parseVersions(JDK.java:375)
        at org.eclipse.payara.tools.sdk.server.JDK.getVersion(JDK.java:234)
        at org.eclipse.payara.tools.sdk.server.ServerTasks.startServer(ServerTasks.java:159)
        at org.eclipse.payara.tools.server.starting.PayaraStartJob.startPayara(PayaraStartJob.java:177)
        at org.eclipse.payara.tools.server.starting.PayaraStartJob.call(PayaraStartJob.java:68)
        at org.eclipse.payara.tools.server.starting.PayaraStartJob.call(PayaraStartJob.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### Environment

* OS: Ubuntu 19.10
* Java: 1.8.0_232-ea-8u232-b09-0ubuntu1-b09
* Eclipse: 2019-09 R (4.13.0)
* Payara Tools: 1.0.0.201909271753

**Comment by hjoeren** [comment]
Okay, trying a little while I found a solution:

With an initial installation of eclipse there is only one installed JRE listed in the settings (`Preferences` `>` `Java` `>` `Installed JREs`):
```
| Name                           | Location                          | Type        |
|--------------------------------|-----------------------------------|------------ |
| java-8-openjdk-amd64 (default) | /usr/lib/jvm/java-8-openjdk-amd64 | Standard VM |
```
With this setting, it isn't possible to start payara like mentioned above. But now: After searching additional JREs (in the `/usr/lib/jvm` directory) **but not changing the default**, the settings are like this:

```
| Name                           | Location                              | Type        |
|--------------------------------|---------------------------------------|------------ |
| java-8-openjdk-amd64 (default) | /usr/lib/jvm/java-8-openjdk-amd64     | Standard VM |
| java-1.8.0-openjdk-amd64       | /usr/lib/jvm/java-1.8.0-openjdk-amd64 | Standard VM |
| ...                            | ...                                   | ...         |
```
After applying this settings it is possible to start a server without an error. I don't know if this is a matter of eclipse, a matter of payara tools or a problem at all.

**Comment by arjantijms** [comment]
You can pretty much follow the issue from the stack. 

`JDK.parseVersions` means it attempts to see what JDK version you have, and then "232-ea" doesn't, of course, parse into an integer.

From your installed JDK version, it's clear where "232-ea" comes from: "1.8.0_232-ea-8u232-b09-0ubuntu1-b09"

As you can see [here](https://github.com/payara/ecosystem-eclipse-plugin/blob/master/plugins/org.eclipse.payara.tools/src/org/eclipse/payara/tools/sdk/server/JDK.java#L73) none of the devs working on that class ever took such exotic version number into account.

This should be an easy fix for @jGauravGupta Likely Netbeans (which shares this class) has a similar issue.

**Comment by jGauravGupta** [comment]
Hi @hjoeren,

Thanks for reporting the issue, Created the internal issue EP-47 to address it.

**Comment by jGauravGupta** [comment]
Fixed by https://github.com/payara/ecosystem-eclipse-plugin/pull/20
